### ISSUE TITLE
Option to hide icon in phone launcher

### ISSUE THREAD

**Issue by dgw** [dheera/android-wearface-matrix#2]
Most watch faces I've installed either don't have an icon in the phone's app launcher at all, or offer an option to hide it.

**Comment by nemchik** [comment]
The icon on the phone could be useful to change configurations of the watch face if those are added in the future.

**Comment by dgw** [comment]
Updating this watch face to Android Wear 2.0 will bring this along naturally, because AW2.0 watch faces can be installed directly on the wearable.
